### ISSUE TITLE
How to compile under Linux, only windows and macos in the document

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ajaxray/four-in-a-row#1]
How to compile under Linux, only windows and macos in the document

**Comment by ajaxray** [comment]
If you are building for native Linux OS, just the following should work (if dependencies are OK).
```bash
go build -ldflags="-s -w" -o four-in-a-row
# Run it now
./four-in-a-row
```

Or, if you are trying to compile for Linux from other OS, try (for example - ubuntu 64bit)
```bash
env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o four-in-a-row
```

**Comment by Yakumo-Yukari** [comment]
> If you are building for native Linux OS, just the following should work (if dependencies are OK).
> 
> ```shell
> go build -ldflags="-s -w" -o four-in-a-row
> # Run it now
> ./four-in-a-row
> ```
> 
> Or, if you are trying to compile for Linux from other OS, try (for example - ubuntu 64bit)
> 
> ```shell
> env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o four-in-a-row
> ```

Thank you.
